version: '3.4'

services:
  ninja:
    image: scireum/s3-ninja:8.3.1
    restart: always
    user: root
    ports:
      - 9000:9000
    volumes:
      - ./data:/home/sirius/data
  run:
    image: camelotindocker
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    restart: always
    command: sleep infinity
    depends_on:
      - ninja
    environment:
      - AWS_S3_ENDPOINT_URL=http://ninja:9000
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
